import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { mega } from "@/function/functions";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

    const [qtde, setQtde] = useState(6)
    const [numeros, setNumeros] = useState([])

    useEffect(() => {
        setNumeros(mega(qtde))
    }, []);

    function renderizarNumeros() {
        return numeros.map((numero) => [
            <span key={numero}>{numero}</span>
        ])
    }
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.titulo}>Desafio Mega-Sena</h1>

                <div className={styles.form}>
                    <button onClick={() => {setNumeros(mega(qtde))}}>Gerar Números</button>
                    <input
                        type="number"
                        name="Qtde"
                        value={qtde}
                        onChange={event => setQtde(event.target.value)}
                    />
                </div>

                <div className={styles.numbers}>{renderizarNumeros()}</div>
            </main>
        </>
    );
}
