import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [dezenas, setDezenas] = useState([])
    const [qtde, setQtde] = useState(6);

    function alterarQtde(value) {
        setQtde(value);
    }

    function limparNumeros() {

      let tamanhoArray = dezenas.length;
      console.log(tamanhoArray);

    }

    function gerarNumeros() {

      limparNumeros()

      const arrayNumeros = []

        for (let i = 1; i <= qtde; i++) {
            arrayNumeros.push(<span key={i}>{Math.floor(Math.random() * 60)}</span>)
        }

        console.log(arrayNumeros);

        setDezenas([...dezenas, arrayNumeros])

        return dezenas;
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main} onLoad={limparNumeros}>
                <h1 className={styles.titulo}>Desafio Mega-Sena</h1>

                <div className={styles.form}>
                    <button onClick={gerarNumeros}>Gerar Números</button>
                    <input
                        type="number"
                        name="Qtde"
                        value={qtde}
                        onChange={(e) => alterarQtde(e.target.value)}
                    />
                </div>

                <div className={styles.numbers}>{dezenas}</div>
            </main>
        </>
    );
}
