import styles from "../styles/Home.module.css";
import Head from "next/head";
import Questao from "../../components/Questao";
import QuestaoModel from "../../model/Questao";
import RespostaModel from "../../model/Resposta";
import { useState } from "react";

const questaoMock = new QuestaoModel(1, "Melhor cor?", [
  RespostaModel.errada("Verde"),
  RespostaModel.errada("Vermelha"),
  RespostaModel.errada("Azul"),
  RespostaModel.certa("Preta"),
]);

export default function Home() {

  const [questao, setQuestao] = useState(questaoMock);

  function respostaFornecida(indice: number) {
    console.log(indice);
    setQuestao(questao.responderCom(indice));
  }

  return (
    <>
      <Head>
        <title>Quiz com Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <Questao valor={questao} respostaFornecida={respostaFornecida} />
      </main>
    </>
  );
}
