import Head from "next/head";
import Questao from "../../components/Questao";
import QuestaoModel from "../../model/Questao";
import RespostaModel from "../../model/Resposta";

export default function Home() {
  const questaoTeste = new QuestaoModel(1, "Melhor cor?", [
    RespostaModel.errada('Verde'),
    RespostaModel.errada('Vermelha'),
    RespostaModel.errada('Azul'),
    RespostaModel.certa('Preta'),
  ]);
  return (
    <>
      <Head>
        <title>Quiz com Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Questao valor={questaoTeste}/>
      </main>
    </>
  );
}
